### PR TITLE
fixed bug where extra fields on a different form on the same page could ...

### PR DESCRIPTION
**Pull request by chrissilich**
...throw errors after validation

on pages with 2 forms, i.e. login or register, a failed validation on
one form would cause undefined index errors if the other form had any
custom fields.

### CODE REVIEW

**Comment by butlerblog** [comment]
The next release will be 3.0 and that file is going to be changed (and moved), so I'm past merging it.  However, the change will be included because it's a valid point.

This does only effect situations where the process is not the plugin's own forms and the WP process is being used (which is forms where the WP register_form filter hook is used that are displayed on pages other than wp-login.php).  But since that probably includes implementations with WooCommerce and this plugin is becoming more widely used in conjunction with WC, it's a valid concern.  (Also, the same test is there for select and textarea fields, so not sure why I didn't already do that for the others.)

**Comment by chrissilich** [comment]
Yeah, I wondered too.

Any idea why the "required" options on my custom fields for registration
aren't being required? I'm assuming it's the 2 forms on one page problem
again, and I'll have to move registration to it's own page.

**Comment by butlerblog** [comment]
wpmem_wp_reg_validate checks for required fields. It is hooked to the registration_errors filter.  If that doesn't run on a custom form, then required fields won't be validated.

**Comment by chrissilich** [comment]
I'm not that much of a wordpress geek, so you're speaking... not greek, but
maybe old english to me. Can you help me out in more detail, or tell me
what I can check on to diagnose the problem?

Thanks so much Chad.

**Comment by butlerblog** [comment]
That depends on a few things, but I want to avoid this turning into a support thread. It started as a pull request which is fine, and I do provide support for the plugin, but this is the wrong channel for that.
1. If you use the plugin's own forms, you don't have to worry about field validation; that's already managed.  
2. Likewise, if the WP registration process is used (wp-login.php?action=register) that's also already managed (using the registration_errors filter hook).  
3. If you are using some other registration process that uses WP's register_form filter then fields created through WP-Members will be added, but field validation needs to be hooked to the registration_errors filter.  if it's a third party setup, if it's built using the three primary hooks for registration (see below) it should be fine. But because it's outside the plugin, I don't know what it is and how it's put together so I can't really answer much on it.
4. If you are creating your own custom registration, same thing as above - the [registration_errors filter hook](http://codex.wordpress.org/Plugin_API/Filter_Reference/registration_errors) is what the plugin hooks to for validating the fields.

If it's 3 or 4 the process needs to use three hooks (two actions and one filter) - register_form, registration_errors, and user_register.  If that doesn't make sense, then use # 1.  There is plenty of [free documentation on the support site](http://rocketgeek.com/) (as well as a lot of premium tutorials) on how to set it up.

**Pull request closed without merging**
